---
apiVersion: v1
kind: Namespace
metadata: 
  name: nwapp
  labels:
    version: v1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwapp-config
  namespace: nwapp
data:
  db_host: nwdb-svc.nwapp.svc.cluster.local
  db_user: root


---
apiVersion: v1
kind: Secret
metadata:
  name: nwapp-secret
  namespace: nwapp
data:
  # hello,world
  db_password: aGVsbG8sd29ybGQ=